// Generated by CoffeeScript 1.6.2
var $, member, parseMsg, valConstraints, valMessages;

if (typeof valMessages === "undefined" || valMessages === null) {
  valMessages = {
    validateRequired: {
      successmsg: '',
      errormsg: 'I am sorry but this is required!'
    },
    validateRangeLength: {
      successmsg: '',
      errormsg: 'Sorry, the length is meant to be between %s and %s characters!'
    },
    validateMinLength: {
      successmsg: '',
      errormsg: 'Please provide at least %s characters'
    },
    validateEmail: {
      successmsg: '',
      errormsg: 'This does not look like a valid E-Mail address to me'
    },
    validateRegexp: {
      successmsg: '',
      errormsg: 'Something is wrong!'
    }
  };
}

valConstraints = {
  validateRequired: function() {
    return {
      valfun: function(str) {
        if (str.length >= 1) {
          return true;
        } else {
          return false;
        }
      },
      successmsg: valMessages.validateRequired.successmsg,
      errormsg: valMessages.validateRequired.errormsg
    };
  },
  validateRangeLength: function(ml) {
    return {
      valfun: function(str) {
        var _ref;

        if ((ml[0] <= (_ref = str.length) && _ref <= ml[1])) {
          return true;
        } else {
          return false;
        }
      },
      successmsg: parseMsg(valMessages.validateRangeLength.successmsg, ml),
      errormsg: parseMsg(valMessages.validateRangeLength.errormsg, ml)
    };
  },
  validateMinLength: function(rl) {
    return {
      valfun: function(str) {
        if (str.length >= parseInt(rl)) {
          return true;
        } else {
          return false;
        }
      },
      successmsg: parseMsg(valMessages.validateMinLength.successmsg, rl),
      errormsg: parseMsg(valMessages.validateMinLength.errormsg, rl)
    };
  },
  validateEmail: function() {
    return {
      valfun: function(str) {
        var exp;

        exp = /^(.{1,})@(.{1,})\.(.{1,})$/;
        if (str.match(exp) != null) {
          return true;
        } else {
          return false;
        }
      },
      successmsg: valMessages.validateEmail.successmsg,
      errormsg: valMessages.validateEmail.errormsg
    };
  },
  validateRegexp: function(exp) {
    return {
      valfun: function(str) {
        if (str.match(exp) != null) {
          return true;
        } else {
          return false;
        }
      },
      successmsg: valMessages.validateRegexp.successmsg,
      errormsg: valMessages.validateRegexp.errormsg
    };
  }
};

$ = jQuery;

$.fn.extend({
  validate: function(options) {
    var ValidationObj, createLi, hideMessages, log, settings, showMessages;

    settings = {
      debug: false,
      onKeyUpValidationSuccess: function(elem, messages) {
        return hideMessages(elem);
      },
      onKeyUpValidationError: function(elem, messages) {
        hideMessages(elem);
        return showMessages(elem, messages);
      },
      onBlurValidationSuccess: function(elem, messages) {
        return hideMessages(elem);
      },
      onBlurValidationError: function(elem, messages) {
        hideMessages(elem);
        return showMessages(elem, messages);
      },
      onSubmitElemValidationSuccess: function(elem, messages) {
        return hideMessages(elem);
      },
      onSubmitElemValidationError: function(elem, messages) {
        hideMessages(elem);
        return showMessages(elem, messages);
      },
      onSubmitValidationSuccess: function(form) {},
      onSubmitValidationError: function(form) {},
      onEmpty: function(elem) {
        return hideMessages(elem);
      },
      validateOnKeyUp: false,
      validateOnBlur: true,
      validateOnSubmit: true,
      useFormPOST: true,
      ulClass: 'valUl',
      liClass: 'valLi'
    };
    settings = $.extend(settings, options);
    hideMessages = function(elem) {
      var errorList;

      errorList = elem.next('ul');
      return errorList.remove();
    };
    showMessages = function(elem, messages) {
      var $messages, errorList, message, _i, _len;

      $messages = messages.failed.map(createLi);
      errorList = $('<ul>').addClass(settings.ulClass);
      for (_i = 0, _len = $messages.length; _i < _len; _i++) {
        message = $messages[_i];
        errorList.append(message);
      }
      return errorList.insertAfter(elem);
    };
    createLi = function(error) {
      return $('<li>' + error + '</li>').addClass(settings.liClass);
    };
    log = function(msg) {
      if (settings.debug) {
        return typeof console !== "undefined" && console !== null ? console.log(msg) : void 0;
      }
    };
    ValidationObj = (function() {
      function ValidationObj(elem) {
        this.elem = elem;
        this.data = this.elem.data();
        this.valFuncs = this.parseValFuncs();
        this.minval = this.elem.data('validate-minval') || 0;
        if (this.elem.is('input') || this.elem.is('textarea')) {
          if (settings.validateOnKeyUp) {
            this.startKeyUpValidation();
          }
          if (settings.validateOnBlur) {
            this.startBlurValidation();
          }
        }
        if (this.elem.is('select') || this.elem.is('checkbox')) {
          this.startClickValidation();
        }
      }

      ValidationObj.prototype.parseValFuncs = function() {
        var errexp, errfunc, func, succexp, succfunc, valFuncs, valkey, value, _ref, _ref1;

        errexp = /^(.*)Errormsg$/;
        succexp = /^(.*)Successmsg$/;
        _ref = this.data;
        for (valkey in _ref) {
          value = _ref[valkey];
          errfunc = valkey.match(errexp);
          succfunc = valkey.match(succexp);
          if (errfunc != null) {
            if (errfunc[1] != null) {
              valMessages[errfunc[1]].errormsg = value;
            }
          }
          if (succfunc != null) {
            if (succfunc[1] != null) {
              valMessages[succfunc[1]].successmsg = value;
            }
          }
        }
        valFuncs = {};
        _ref1 = this.data;
        for (func in _ref1) {
          value = _ref1[func];
          if (member(func, valConstraints)) {
            valFuncs[func] = valConstraints[func](value);
          }
        }
        return valFuncs;
      };

      ValidationObj.prototype.startKeyUpValidation = function() {
        var valObj;

        valObj = this;
        return this.elem.on('keyup', function(e) {
          if (valObj.elem.val() === '' && e.which !== 13) {
            return settings.onEmpty(valObj.elem);
          } else {
            if (valObj.minval != null) {
              if (valObj.elem.val().length >= parseInt(valObj.minval)) {
                return valObj.applyRules('onKeyUpValidation');
              }
            } else {
              return valObj.applyRules('onKeyUpValidation');
            }
          }
        });
      };

      ValidationObj.prototype.startBlurValidation = function() {
        var valObj;

        valObj = this;
        return this.elem.on('blur', function(e) {
          if (valObj.elem.val() !== '') {
            return valObj.applyRules('onBlurValidation');
          } else {
            return settings.onEmpty(valObj.elem);
          }
        });
      };

      ValidationObj.prototype.startClickValidation = function() {};

      ValidationObj.prototype.applyRules = function(eventFunc) {
        var funcName, funcObj, messages, _ref;

        messages = {
          success: [],
          failed: []
        };
        _ref = this.valFuncs;
        for (funcName in _ref) {
          funcObj = _ref[funcName];
          if (funcObj.valfun(this.elem.val()) === false) {
            messages.failed.push(funcObj.errormsg);
          } else {
            messages.success.push(funcObj.successmsg);
          }
        }
        if (messages.failed.length === 0) {
          settings[eventFunc + 'Success'](this.elem, messages);
          return true;
        } else {
          settings[eventFunc + 'Error'](this.elem, messages);
          return false;
        }
      };

      return ValidationObj;

    })();
    return this.each(function() {
      var applyAllRules, formObj, validationObjects;

      validationObjects = [];
      $(this).find('input, select, textarea').each(function(i) {
        if ($(this).attr('type') !== 'submit') {
          return validationObjects[i] = new ValidationObj($(this));
        }
      });
      formObj = $(this);
      if (settings.validateOnSubmit) {
        $(this).on('submit', function(e) {
          if (!applyAllRules(validationObjects)) {
            e.preventDefault();
            return settings.onSubmitValidationError(formObj);
          } else {
            if (!settings.useFormPOST) {
              e.preventDefault();
            }
            return settings.onSubmitValidationSuccess(formObj);
          }
        });
      }
      return applyAllRules = function(validationObjects) {
        var success, valObj, _i, _len;

        success = true;
        for (_i = 0, _len = validationObjects.length; _i < _len; _i++) {
          valObj = validationObjects[_i];
          if (!valObj.applyRules('onSubmitElemValidation')) {
            success = false;
          }
        }
        return success;
      };
    });
  }
});

member = function(aKey, obj) {
  var elem, key, val, _i, _len;

  if (Array.isArray(obj)) {
    for (_i = 0, _len = obj.length; _i < _len; _i++) {
      elem = obj[_i];
      if (elem === aKey) {
        return true;
      }
    }
  } else {
    for (key in obj) {
      val = obj[key];
      if (key === aKey) {
        return true;
      }
    }
  }
  return false;
};

parseMsg = function(msg, params) {
  var i, message, param, _i, _len;

  if (msg.indexOf('%s') === -1) {
    return msg;
  } else {
    if (typeof params === 'object') {
      message = msg.split('%s')[0];
      for (i = _i = 0, _len = params.length; _i < _len; i = ++_i) {
        param = params[i];
        message += param + msg.split('%s')[i + 1];
      }
      return message;
    } else {
      return msg.split('%s')[0] + params + msg.split('%s')[1];
    }
  }
};
